### ISSUE TITLE
Get rid of UI notification

### ISSUE THREAD

**Issue by ghost** [brettferdosi/grayscale#5]
Everytime Grayscale turns on/off, a UI element comes on-screen and I'd like to disable it. Could you add this as an option? Thank you <3

**Comment by brettferdosi** [comment]
This is an OS-level behavior that isn't controlled by the grayscale app. If you go into System Preferences and toggle the grayscale filter that way, the UI element still comes up. When I initially developed the app on Big Sur, there wasn't any kind of pop up, and I agree that it would be nice not to have it. I think it's unlikely that there will be a workaround, but I'll leave this issue open in case I or someone else has time to investigate.
