### ISSUE TITLE
Handle grayscale for multiple monitors

### ISSUE THREAD

**Issue by theredspoon** [brettferdosi/grayscale#6]
Grayscale mode affects one monitor, but if I have multiple monitors hooked up via USB-C or HDMI, those monitors are not impacted by the change to grayscale mode.

**Comment by brettferdosi** [comment]
Hi, I can't reproduce this behavior. For me all displays share the same grayscale status. Could you share some additional info about your setup? Is there anything unusual about your settings in System Preferences > Displays or System Preferences > Accessibility > Display > Color Filters?
