### ISSUE TITLE
Right-click dropdown doesn't work

### ISSUE THREAD

**Issue by mayeaux** [brettferdosi/grayscale#8]
I am not able to trigger the dropdown from a right-click, it just triggers the toggle as if I had left-clicked.

M1, 13.5.2

**Comment by brettferdosi** [comment]
Hi, I run an M1 mac too and can't reproduce this on 14.1.2. Feel free to get in touch if you have any further questions.

**Comment by mayeaux** [comment]
> Hi, I run an M1 mac too and can't reproduce this on 14.1.2. Feel free to get in touch if you have any further questions.

Works now that I've updated to 14.1.2, thanks!
